export function getCategoryStyles(categoryId) {
  const styles = {
    restaurant: {
      bgGradient: "bg-gradient-to-r from-amber-500 to-rose-500",
      buttonGradient:
        "bg-gradient-to-r from-amber-600 to-rose-600 hover:from-amber-500 hover:to-rose-500",
      categoryBg: "bg-amber-100",
      categoryIcon: "text-amber-600",
      categoryText: "text-amber-700",
      tagBg: "bg-rose-50",
      tagText: "text-rose-600",
      priceBg: "bg-amber-50",
      priceText: "text-amber-600",
      ratingBg: "bg-amber-100",
      ratingIcon: "text-amber-500",
      ratingText: "text-amber-700",
      infoIcon: "text-amber-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    dentists: {
      bgGradient: "bg-gradient-to-r from-teal-500 to-cyan-500",
      buttonGradient:
        "bg-gradient-to-r from-teal-600 to-cyan-600 hover:from-teal-500 hover:to-cyan-500",
      categoryBg: "bg-cyan-100",
      categoryIcon: "text-cyan-600",
      categoryText: "text-cyan-700",
      tagBg: "bg-teal-50",
      tagText: "text-teal-600",
      priceBg: "bg-cyan-50",
      priceText: "text-cyan-600",
      ratingBg: "bg-teal-100",
      ratingIcon: "text-teal-500",
      ratingText: "text-teal-700",
      infoIcon: "text-teal-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    hotels: {
      bgGradient: "bg-gradient-to-r from-teal-500 to-cyan-500",
      buttonGradient:
        "bg-gradient-to-r from-teal-600 to-cyan-600 hover:from-teal-500 hover:to-cyan-500",
      categoryBg: "bg-teal-100",
      categoryIcon: "text-teal-600",
      categoryText: "text-teal-700",
      tagBg: "bg-cyan-50",
      tagText: "text-cyan-600",
      priceBg: "bg-teal-50",
      priceText: "text-teal-600",
      ratingBg: "bg-teal-100",
      ratingIcon: "text-teal-500",
      ratingText: "text-teal-700",
      infoIcon: "text-teal-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    schools: {
      bgGradient: "bg-gradient-to-r from-indigo-500 to-violet-500",
      buttonGradient:
        "bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500",
      categoryBg: "bg-indigo-100",
      categoryIcon: "text-indigo-600",
      categoryText: "text-indigo-700",
      tagBg: "bg-violet-50",
      tagText: "text-violet-600",
      priceBg: "bg-indigo-50",
      priceText: "text-indigo-600",
      ratingBg: "bg-indigo-100",
      ratingIcon: "text-indigo-500",
      ratingText: "text-indigo-700",
      infoIcon: "text-indigo-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    colleges: {
      bgGradient: "bg-gradient-to-r from-emerald-500 to-green-500",
      buttonGradient:
        "bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-500 hover:to-green-500",
      categoryBg: "bg-emerald-100",
      categoryIcon: "text-emerald-600",
      categoryText: "text-emerald-700",
      tagBg: "bg-green-50",
      tagText: "text-green-600",
      priceBg: "bg-emerald-50",
      priceText: "text-emerald-600",
      ratingBg: "bg-emerald-100",
      ratingIcon: "text-emerald-500",
      ratingText: "text-emerald-700",
      infoIcon: "text-emerald-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    hospitals: {
      bgGradient: "bg-gradient-to-r from-red-500 to-rose-500",
      buttonGradient:
        "bg-gradient-to-r from-red-600 to-rose-600 hover:from-red-500 hover:to-rose-500",
      categoryBg: "bg-red-100",
      categoryIcon: "text-red-600",
      categoryText: "text-red-700",
      tagBg: "bg-rose-50",
      tagText: "text-rose-600",
      priceBg: "bg-red-50",
      priceText: "text-red-600",
      ratingBg: "bg-red-100",
      ratingIcon: "text-red-500",
      ratingText: "text-red-700",
      infoIcon: "text-red-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    gyms: {
      bgGradient: "bg-gradient-to-r from-orange-500 to-red-500",
      buttonGradient:
        "bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-500 hover:to-red-500",
      categoryBg: "bg-orange-100",
      categoryIcon: "text-orange-600",
      categoryText: "text-orange-700",
      tagBg: "bg-red-50",
      tagText: "text-red-600",
      priceBg: "bg-orange-50",
      priceText: "text-orange-600",
      ratingBg: "bg-orange-100",
      ratingIcon: "text-orange-500",
      ratingText: "text-orange-700",
      infoIcon: "text-orange-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    parks: {
      bgGradient: "bg-gradient-to-r from-green-500 to-lime-500",
      buttonGradient:
        "bg-gradient-to-r from-green-600 to-lime-600 hover:from-green-500 hover:to-lime-500",
      categoryBg: "bg-green-100",
      categoryIcon: "text-green-600",
      categoryText: "text-green-700",
      tagBg: "bg-lime-50",
      tagText: "text-lime-600",
      priceBg: "bg-green-50",
      priceText: "text-green-600",
      ratingBg: "bg-green-100",
      ratingIcon: "text-green-500",
      ratingText: "text-green-700",
      infoIcon: "text-green-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    libraries: {
      bgGradient: "bg-gradient-to-r from-slate-500 to-gray-500",
      buttonGradient:
        "bg-gradient-to-r from-slate-600 to-gray-600 hover:from-slate-500 hover:to-gray-500",
      categoryBg: "bg-slate-100",
      categoryIcon: "text-slate-600",
      categoryText: "text-slate-700",
      tagBg: "bg-gray-50",
      tagText: "text-gray-600",
      priceBg: "bg-slate-50",
      priceText: "text-slate-600",
      ratingBg: "bg-slate-100",
      ratingIcon: "text-slate-500",
      ratingText: "text-slate-700",
      infoIcon: "text-slate-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    publictransport: {
      bgGradient: "bg-gradient-to-r from-yellow-500 to-orange-400",
      buttonGradient:
        "bg-gradient-to-r from-yellow-600 to-orange-500 hover:from-yellow-500 hover:to-orange-400",
      categoryBg: "bg-yellow-100",
      categoryIcon: "text-yellow-600",
      categoryText: "text-yellow-700",
      tagBg: "bg-orange-50",
      tagText: "text-orange-600",
      priceBg: "bg-yellow-50",
      priceText: "text-yellow-600",
      ratingBg: "bg-yellow-100",
      ratingIcon: "text-yellow-500",
      ratingText: "text-yellow-700",
      infoIcon: "text-yellow-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    policestations: {
      bgGradient: "bg-gradient-to-r from-sky-500 to-blue-500",
      buttonGradient:
        "bg-gradient-to-r from-sky-600 to-blue-600 hover:from-sky-500 hover:to-blue-500",
      categoryBg: "bg-sky-100",
      categoryIcon: "text-sky-600",
      categoryText: "text-sky-700",
      tagBg: "bg-blue-50",
      tagText: "text-blue-600",
      priceBg: "bg-sky-50",
      priceText: "text-sky-600",
      ratingBg: "bg-sky-100",
      ratingIcon: "text-sky-500",
      ratingText: "text-sky-700",
      infoIcon: "text-sky-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    salons: {
      bgGradient: "bg-gradient-to-r from-pink-500 to-rose-400",
      buttonGradient:
        "bg-gradient-to-r from-pink-600 to-rose-500 hover:from-pink-500 hover:to-rose-400",
      categoryBg: "bg-pink-100",
      categoryIcon: "text-pink-600",
      categoryText: "text-pink-700",
      tagBg: "bg-rose-50",
      tagText: "text-rose-600",
      priceBg: "bg-pink-50",
      priceText: "text-pink-600",
      ratingBg: "bg-pink-100",
      ratingIcon: "text-pink-500",
      ratingText: "text-pink-700",
      infoIcon: "text-pink-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    bakeries: {
      bgGradient: "bg-gradient-to-r from-yellow-400 to-orange-300",
      buttonGradient:
        "bg-gradient-to-r from-yellow-500 to-orange-400 hover:from-yellow-400 hover:to-orange-300",
      categoryBg: "bg-yellow-100",
      categoryIcon: "text-yellow-600",
      categoryText: "text-yellow-700",
      tagBg: "bg-orange-50",
      tagText: "text-orange-600",
      priceBg: "bg-yellow-50",
      priceText: "text-yellow-600",
      ratingBg: "bg-yellow-100",
      ratingIcon: "text-yellow-500",
      ratingText: "text-yellow-700",
      infoIcon: "text-yellow-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    beaches: {
      bgGradient: "bg-gradient-to-r from-sky-400 to-cyan-300",
      buttonGradient:
        "bg-gradient-to-r from-sky-500 to-cyan-400 hover:from-sky-400 hover:to-cyan-300",
      categoryBg: "bg-sky-100",
      categoryIcon: "text-sky-600",
      categoryText: "text-sky-700",
      tagBg: "bg-cyan-50",
      tagText: "text-cyan-600",
      priceBg: "bg-sky-50",
      priceText: "text-sky-600",
      ratingBg: "bg-sky-100",
      ratingIcon: "text-sky-500",
      ratingText: "text-sky-700",
      infoIcon: "text-sky-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    bookstores: {
      bgGradient: "bg-gradient-to-r from-fuchsia-500 to-purple-400",
      buttonGradient:
        "bg-gradient-to-r from-fuchsia-600 to-purple-500 hover:from-fuchsia-500 hover:to-purple-400",
      categoryBg: "bg-purple-100",
      categoryIcon: "text-purple-600",
      categoryText: "text-purple-700",
      tagBg: "bg-fuchsia-50",
      tagText: "text-fuchsia-600",
      priceBg: "bg-purple-50",
      priceText: "text-purple-600",
      ratingBg: "bg-purple-100",
      ratingIcon: "text-purple-500",
      ratingText: "text-purple-700",
      infoIcon: "text-purple-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    coachingcenters: {
      bgGradient: "bg-gradient-to-r from-rose-500 to-pink-400",
      buttonGradient:
        "bg-gradient-to-r from-rose-600 to-pink-500 hover:from-rose-500 hover:to-pink-400",
      categoryBg: "bg-rose-100",
      categoryIcon: "text-rose-600",
      categoryText: "text-rose-700",
      tagBg: "bg-pink-50",
      tagText: "text-pink-600",
      priceBg: "bg-rose-50",
      priceText: "text-rose-600",
      ratingBg: "bg-rose-100",
      ratingIcon: "text-rose-500",
      ratingText: "text-rose-700",
      infoIcon: "text-rose-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    firestations: {
      bgGradient: "bg-gradient-to-r from-red-600 to-orange-500",
      buttonGradient:
        "bg-gradient-to-r from-red-700 to-orange-600 hover:from-red-600 hover:to-orange-500",
      categoryBg: "bg-red-100",
      categoryIcon: "text-red-600",
      categoryText: "text-red-700",
      tagBg: "bg-orange-50",
      tagText: "text-orange-600",
      priceBg: "bg-red-50",
      priceText: "text-red-600",
      ratingBg: "bg-red-100",
      ratingIcon: "text-red-500",
      ratingText: "text-red-700",
      infoIcon: "text-red-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    temples: {
      bgGradient: "bg-gradient-to-r from-yellow-600 to-amber-500",
      buttonGradient:
        "bg-gradient-to-r from-yellow-700 to-amber-600 hover:from-yellow-600 hover:to-amber-500",
      categoryBg: "bg-yellow-100",
      categoryIcon: "text-yellow-600",
      categoryText: "text-yellow-700",
      tagBg: "bg-amber-50",
      tagText: "text-amber-600",
      priceBg: "bg-yellow-50",
      priceText: "text-yellow-600",
      ratingBg: "bg-yellow-100",
      ratingIcon: "text-yellow-500",
      ratingText: "text-yellow-700",
      infoIcon: "text-yellow-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
    default: {
      bgGradient: "bg-gradient-to-r from-blue-500 to-purple-500",
      buttonGradient:
        "bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500",
      categoryBg: "bg-blue-100",
      categoryIcon: "text-blue-600",
      categoryText: "text-blue-700",
      tagBg: "bg-purple-50",
      tagText: "text-purple-600",
      priceBg: "bg-blue-50",
      priceText: "text-blue-600",
      ratingBg: "bg-blue-100",
      ratingIcon: "text-blue-500",
      ratingText: "text-blue-700",
      infoIcon: "text-blue-500",
      infoLabel: "text-gray-800",
      infoValue: "text-gray-700",
    },
  };

  return styles[categoryId] || styles.default;
}
